# Generated by Django 3.0.6 on 2020-05-30 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('isFolder', models.BooleanField()),
                ('path', models.TextField()),
                ('owner', models.CharField(default='', max_length=30, null=True)),
                ('filesize', models.IntegerField(default=0)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['createdDate'],
            },
        ),
    ]
